export const USERS = [
  {
    id: "12nkjaz232",
    email: "jane.doe@example.com",
    firstName: "Jane",
    lastName: "Doe",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    nationality: "American",
    music: { song: "Shake It Off", singer: "Taylor Swift" },
    isPremium: false,
  },
  {
    id: "124lkjaz231",
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    nationality: "Canadian",
    isPremium: true,
  },
  {
    id: "12nkazeazaz234",
    email: "jane.doe2@example.com",
    firstName: "Jane",
    lastName: "Doe2",
    avatar: "https://randomuser.me/api/portraits/women/51.jpg",
    nationality: "French",
    music: { song: "Love is all", singer: "Beatles" },
    isPremium: true,
  },
  {
    id: "134lazeazedkdjaz233",
    email: "emma.brown@example.com",
    firstName: "Emma",
    lastName: "Brown",
    avatar: "https://randomuser.me/api/portraits/women/47.jpg",
    nationality: "British",
    music: { song: "Someone Like You", singer: "Adele" },
    isPremium: false,
  },
  {
    id: "123Olazkeqsdqs023",
    email: "liam.smith@example.com",
    firstName: "Liam",
    lastName: "Smith",
    avatar: "https://randomuser.me/api/portraits/men/50.jpg",
    nationality: "Australian",
    music: { song: "Down Under" },
    isPremium: false,
  },
  {
    id: "231z2qsdqd3222",
    email: "olivia.jones@example.com",
    firstName: "Olivia",
    lastName: "Jones",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
    nationality: "New Zealander",
    music: { song: "Royals", singer: "Lorde" },
    isPremium: true,
  },
];
